### ISSUE TITLE
Need Clarification

### ISSUE THREAD

**Issue by afaucogney** [metova/Cappuccino#3]
I have been excited by reading the Android Weekly with your project, however by reading the Readme, I understand that you have to inform in the app, every process that may handle delay (animation, async task...). Is that right ?

I'm surprise of this, because even if the no-opp version disable the lib process outside of test phase, putting test decencies in app it no stat of the art. What do you think ?

To be clear, I understand the problem ! this is your solution that trigger question to me.

Friendly Anthony

**Comment by trobalik** [comment]
What is "state of the art", really? To me, comprehensive testing is state of the art, and the benefits of making that easier outweighed the small downside of having some no-op library code in your production release. By the way, I was actually inspired to create this solution by observing what Square does with their LeakCanary library -- is LeakCanary not "state of the art," then?

**Comment by afaucogney** [comment]
Hi @trobalik, please do not be obfuscated, this is not my aim, I just want get background.

My question is not about no-op topic, that is of course a very good thing from Square as from you, my point if more about writing done in every part of code that:
- need to be tested
- is async
a piece of code that belong to your lib. I mean there is not anymore a clear separation of concern.

I know what you tried to solve, and really understand your solution, but maybe someone may have another (maybe better) solution.

**Comment by bholota** [comment]
I will join this discussion - so your api still require manual call that tells 'we're iddle now' for example for async activity change? And it's all about simplifying messy espresso api? (nice work by the way).

I think that readme need more clarifications when it comes to samples because right now it's for ppl who already did some iddling resources via clean espresso. Also can you explain why there is no-op version? By default androidTest code shouldn't be added to release version.

**Comment by trobalik** [comment]
@bholota, yes, it's about simplifying the Espresso API so devs don't have to roll their own custom IdlingResources, and also about making it as easy as possible to notify Espresso about custom asynchronous processes. The simplest solution was to make it possible to make Cappuccino calls within the codebase itself. Obviously, I didn't want those calls to *do* anything in release, and so I created a no-op version of the library, following Square's example with [LeakCanary](https://github.com/square/leakcanary). If there weren't a no-op version, then you wouldn't even be able to compile a release variant without first removing all the Cappuccino calls.

**Comment by bholota** [comment]
Oh, I got it now, just investigated sample app. So Cappuccino has white-box approach - resource watcher has to be implemented also in app code, it's clear now.
