### ISSUE TITLE
Support for simpler view matching via Testing Tags

### ISSUE THREAD

**Issue by zphensley42** [metova/Cappuccino#4]
Recently, while testing lists of items that provide multiple views I favored modifying content descriptions based on the view model associated with an item position. Doing this, I was able to easily match a view using withContentDescription. This is much simpler than using the numerous combined matches from before with allOf().

As we don't want to overwrite the proper content descriptions according to our accessibility guides, providing a method of matching according to some specific testing tag would be great. This testing tag should only be available during testing environments, similar to how idle resources work now.

Bonus points for determining some easy method of automagically adding these tags, but utility methods are the baseline.

**Comment by trobalik** [comment]
Closing this issue, as it is now implemented with Cappuccino version 0.8.1.
