### ISSUE TITLE
Question: Is it possible to disable animations using Cappuccino on M+ devices?

### ISSUE THREAD

**Issue by ardock** [metova/Cappuccino#6]
I'm trying it with no luck and I read about your plugin [here](http://stackoverflow.com/questions/38124136/unable-to-grant-set-animation-scale-permission-programatically).

**Comment by autonomousapps** [comment]
Yes, absolutely it works on Marshmallow and greater. Have you followed all the instructions? There are several critical steps. Please report what you've tried.

**Comment by ardock** [comment]
Awesome, thanks, I'm using the same reflection methods but not Cappuccino.

I thought it was not possible because my alternative works for previous versions only.

I think that I know what it's happenning, I'm going to confirm this and then update my response.

I'm very interested in this topic and your plugin but my holidays ending this week.

I'll try to contribute or offer feedback in the future, thanks for answer.

**Comment by ardock** [comment]
Sorry my question was wrong.

 Is it possible to disable animations using Cappucino on M+ ARM emulators? Did you try it? 

Mine also works on M+ devices but not on emulators due to [this](https://travis-ci.org/ardock/android-topeka/jobs/153158643#L1858):

```
:app:installDebug
Installing APK 'app-debug.apk' on 'test(AVD) - 6.0' for app:debug
Installed on 1 device.
:app:grantSetAnimationScalePermission
Operation not allowed: java.lang.SecurityException: Permission android.permission.SET_ANIMATION_SCALE is not a changeable permission type
:app:connectedDebugAndroidTest
```

I found this [fix](https://android.googlesource.com/platform/frameworks/base/+/9f5b0a2%5E!/).
There was a [bug](https://code.google.com/p/android-developer-preview/issues/detail?id=3229) on M preview.

```
-        if (!bp.isRuntime()) {
+        if (!bp.isRuntime() && !bp.isDevelopment()) {
             throw new SecurityException("Permission " + bp.name
                     + " is not a changeable permission type");
```

From [here](https://github.com/MindMac/Android-PermissionsLevelDescMap/blob/master/permissions.py) or [here](https://github.com/android/platform_frameworks_base/blob/master/core/res/AndroidManifest.xml), I understand this is a development permission:
`"android.permission.SET_ANIMATION_SCALE" : ["signature|system|development", "Modify the global animation scaling factor. Not for use by third-party applications."], `

I'll try to update tools and your plugin on a M+ emulator, perhaps arm emulator it's not fixed.

**Comment by trobalik** [comment]
Please let me know when and if that gets resolved. I'm very interested. Thanks.

**Comment by ardock** [comment]
Really it's already fixed and merged, the next day this emulator was built, and I don't think they'll update it.

![screenshot at 2016-08-20 10 36 04](https://cloud.githubusercontent.com/assets/1142360/17834470/e8a6608e-6741-11e6-9d26-88bb182d96a6.png)

![screenshot at 2016-08-21 01 49 14](https://cloud.githubusercontent.com/assets/1142360/17834472/ee7575f4-6741-11e6-9fc9-954ff3084d31.png)
