### ISSUE TITLE
Manifest Merge Conflict with espresso-intents

### ISSUE THREAD

**Issue by FabioCB** [metova/Cappuccino#7]
Updating Espresso to espresso 2.2.2 (espresso-intents) it gives a Manifest Merge Conflict with Cappuccino on application label.

Can you add **xmlns:tools="http://schemas.android.com/tools"** and **tools:replace="android:label** to Cappuccino manifest ?

Here is the error:
> java.lang.RuntimeException: Manifest merger failed : Attribute application@label value=(Intents) from [com.android.support.test.espresso:espresso-intents:2.2.2] AndroidManifest.xml:24:18-41
  	is also present at [com.metova:cappuccino:0.8.1] AndroidManifest.xml:12:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element

**Comment by trobalik** [comment]
I'm using Espresso 2.2.2 in my project, and I see no such issues. Can you show me what your Cappuccino dependencies look like in your `dependencies {}` block? Here's mine:

```
    debugCompile("com.metova:cappuccino:0.8.1") {
        transitive = false
    }
    releaseCompile "com.metova:cappuccino-no-op:0.8.1"
```

Note the `transitive = false`. This ensures that Cappuccino's transitive dependencies shouldn't interfere with your app's direct dependencies.

**Comment by FabioCB** [comment]
Here are my Cappuccino dependencies:

    androidTestCompile('com.metova:cappuccino:0.8.1') {
        transitive = false
    }

    releaseCompile "com.metova:cappuccino-no-op:0.8.1"

I need to use androidTestCompile in order to access the Cappuccino animations plugin in Espresso Tests

**Comment by trobalik** [comment]
I was able to replicate your issue locally. Turns out the `androidTestCompile` scope behaves differently than the `debugCompile` scope! Who knew?

Per your request, I added the `tools:replace="android:label"` to the libraries two manifests (including the no-op manifest). For good measure, I've also updated the version of Espresso-core used by the library to 2.2.2. I've tested locally, and all seems well.

Please update to version 0.9 and let me know if that resolves your issues. Thanks for reporting.

**Comment by FabioCB** [comment]
@trobalik  thank you for your support , but I am still having the same issue.

> java.lang.RuntimeException: Manifest merger failed : Attribute application@label value=(Intents) from [com.android.support.test.espresso:espresso-intents:2.2.2] AndroidManifest.xml:24:18-41
  	is also present at [com.metova:cappuccino:0.9] AndroidManifest.xml:13:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element 

Here are my dependencies for Cappuccino and Espresso:

    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'

    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-intents:2.2.2'
    androidTestCompile('com.android.support.test.espresso:espresso-contrib:2.2.2') {
        exclude module: 'recyclerview-v7'
        exclude module: 'support-v4'
        exclude module: 'appcompat-v7'
        exclude module: 'design'
    }

    androidTestCompile('com.metova:cappuccino:0.9') {
        transitive = false
    }
    releaseCompile "com.metova:cappuccino-no-op:0.9"

**Comment by trobalik** [comment]
I can confirm that if I change the dependency scope from debugCompile to androidTestCompile with Cappuccino 0.8.1, then I see the error you describe. However, when I update to 0.9, I no longer see the error.

The project is very simple to contribute to (you can do everything in Android Studio), so please feel free to submit a patch that addresses your issue.

Also, I have to ask the standard questions: did you clean? Did you try invalidate cache and restart?

These are my deps:

```
    androidTestCompile("com.metova:cappuccino:0.9") {
        transitive = false
    }
    releaseCompile "com.metova:cappuccino-no-op:0.9"

    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-web:2.2.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-intents:2.2.2'
    androidTestCompile('com.android.support.test.espresso:espresso-contrib:2.2.2') {
        exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'design'
        exclude module: 'recyclerview-v7'
    }
```
